# Generated by Django 6.0.3 on 2026-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('gastoId', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('coste', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GastoApartamento',
            fields=[
                ('gastoApartamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagoEstado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pagoId', models.AutoField(primary_key=True, serialize=False)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=20)),
            ],
        ),
    ]
