# Generated by Django 6.0.3 on 2026-03-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanza', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoapartamento',
            name='apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.apartamento'),
        ),
        migrations.AddField(
            model_name='gastoapartamento',
            name='gasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanza.gasto'),
        ),
        migrations.AddField(
            model_name='pago',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='operaciones.contrato'),
        ),
    ]
