# Generated by Django 6.0.3 on 2026-03-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=128)),
                ('permisos', models.CharField(choices=[('admin', 'Admin'), ('cobrador', 'Cobrador'), ('mantenimiento', 'Mantenimiento')], default='mantenimiento', max_length=20)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('inquilinoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('fecha_reg', models.DateField(auto_now_add=True)),
                ('apartamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquilinos', to='operaciones.apartamento')),
            ],
        ),
    ]
